### ISSUE TITLE
Request: Cell reordering 

### ISSUE THREAD

**Issue by francescopetrungaro** [composed-swift/ComposedUI#1]
It will be great to have cell reordering functionality implemented. 

Thanks

**Comment by shaps80** [comment]
Currently in progress 👍

**Comment by shaps80** [comment]
@RedPlumber this is now implemented in v1.0.2, sorry it took so long. Let me know if you need support on this or if anything is missing. Keep in mind, you can only drag and drop (or reorder) within the same section. I will eventually build an API for dragging between sections but its non-trivial.
