### ISSUE TITLE
Use of undeclared type 'MoveHandler'

### ISSUE THREAD

**Issue by powerwolf543** [composed-swift/ComposedUI#2]
Hi,
I have cloned the `1.0.1` release.
But I can't build `ComposeUI` because I can't find the type of `MoveHandler `.
Did I miss anything?

**Comment by shaps80** [comment]
Sounds like you're using 'master' rather than a release version. Master should be considered 'develop'. Ensure you're version pinning and all should work fine as it is for all other projects.
Let me know how you get on. Thanks.

**Comment by powerwolf543** [comment]
Oh, I made a mistake. As you said, I am in the `master` not in the release commit. I will checkout the release tag, thanks.

**Comment by shaps80** [comment]
> Oh, I made a mistake. As you said, I am in the `master` not in the release commit. I will checkout the release tag, thanks.

No worries easy mistake. 

FYI the drag and drop (move handler) code will be in the next release or 2. It's done just need to tidy up the implementation/api.

So if you were looking for that support, it's coming.
